# config.yml

backend:
  name: git-gateway
  branch: main # আপনার গিটহাব রিপোজিটরির মেইন ব্রাঞ্চের নাম

# আপনার রিপোজিটরির সাথে কানেক্ট করার জন্য। "owner/repo" এর জায়গায় আপনার ইউজারনেম/রিপোজিটরির নাম দিন।
# যেমন: "your-username/affitimes"
repo: "owner/repo" 

# এটি Decap CMS কে আপনার data.js ফাইলটিকে JSON হিসেবে পড়তে এবং লিখতে সাহায্য করবে
media_folder: "" # যেহেতু আমরা মিডিয়া আপলোড করছি না, এটি খালি থাকবে
public_folder: ""

# ফাইলটিকে JSON ফরম্যাটে চেনার জন্য
collections:
  - name: "database"
    label: "সাইটের ডেটা"
    files:
      - label: "প্রধান ডেটাবেজ"
        name: "database"
        file: "data.js" # আপনার ডেটা ফাইলের সঠিক পাথ
        
        # ফাইলটি JS ফরম্যাটে আছে, কিন্তু আমরা একে JSON-এর মতো করে এডিট করবো
        parser:
          format: "json-frontmatter" # এটি JS অবজেক্টকে YAML/JSON এর মতো করে হ্যান্ডেল করতে পারে
          frontmatter_delimiter: "const database = " # ফাইলের শুরুতে এই লেখাটি খুঁজে বের করবে

        fields:
          - label: "Subjects (Admission Series)"
            name: "subjects"
            widget: "list"
            fields:
              - { label: "Key (e.g., phys1)", name: "key", widget: "string" }
              - { label: "Name (English)", name: "name", widget: "string" }
              - { label: "Name (Bangla)", name: "bn_name", widget: "string" }
              - label: "Chapters"
                name: "chapters"
                widget: "list"
                fields:
                  - { label: "Chapter ID (e.g., phys1_ch1)", name: "id", widget: "string" }
                  - { label: "Chapter Name (English)", name: "name", widget: "string" }
                  - { label: "Chapter Name (Bangla)", name: "bn_name", widget: "string" }
          
          - label: "Videos"
            name: "videos"
            widget: "object"
            # ভিডিও যোগ করা একটু জটিল হতে পারে কারণ এগুলো key-value পেয়ারে আছে
            # সহজ ব্যবস্থাপনার জন্য, ভিডিওগুলোকে লিস্ট হিসেবে রাখা ভালো
            # বর্তমান কাঠামোর জন্য, আপনাকে key (যেমন: phys1_ch2_lec1) এবং value (বাকি তথ্য) আলাদাভাবে যোগ করতে হবে
            # একটি সহজ বিকল্প হতে পারে ভিডিওর জন্য একটি ডেডিকেটেড JSON ফাইল ব্যবহার করা
            summary: "এখানে সব ভিডিও যোগ, এডিট বা ডিলিট করুন"
            fields:
              - label: "All Videos (Key-Value)"
                name: "entries"
                widget: "list"
                summary: "{{fields.key}}"
                fields:
                  - { label: "Video Key (e.g., phys1_ch2_lec1)", name: "key", widget: "string" }
                  - label: "Video Details"
                    name: "details"
                    widget: "object"
                    fields:
                      - { label: "Chapter ID", name: "chapterId", widget: "string" }
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "YouTube Video ID", name: "youtubeId", widget: "string" }
                      - label: "Instructor"
                        name: "instructor"
                        widget: "object"
                        fields:
                          - { label: "Name", name: "name", widget: "string" }
                      - label: "Downloads"
                        name: "downloads"
                        widget: "object"
                        fields:
                          - { label: "Lecture Sheet URL", name: "lectureSheet", widget: "string" }