# *** চূড়ান্ত কনফিগারেশন ***
backend:
  name: github # পরিবর্তন এখানে: git-gateway এর বদলে github
  repo: boyhac1/affitimes- # আপনার রিপোজিটরির নাম
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "main_database"
    label: "সাইটের সকল ডেটা"
    files:
      - label: "প্রধান ডেটাবেজ"
        name: "database"
        file: "data.js"
        
        parser:
          format: "json-frontmatter"
          frontmatter_delimiter: "const database = "

        fields:
          - label: "Admission Subjects"
            name: "subjects"
            widget: "list"
            summary: "{{fields.name}} - {{fields.bn_name}}"
            fields:
              - { label: "Subject ID (e.g., phys1)", name: "id", widget: "string" }
              - { label: "Name (English)", name: "name", widget: "string" }
              - { label: "Name (Bangla)", name: "bn_name", widget: "string" }
              - label: "Chapters"
                name: "chapters"
                widget: "list"
                summary: "{{fields.name}}"
                fields:
                  - { label: "Chapter ID", name: "id", widget: "string" }
                  - { label: "Chapter Name (English)", name: "name", widget: "string" }
                  - { label: "Chapter Name (Bangla)", name: "bn_name", widget: "string" }
          
          - label: "HSC One Shot Subjects"
            name: "oneShotSubjects"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Subject ID", name: "id", widget: "string" }
              - { label: "Name (English)", name: "name", widget: "string" }
              - { label: "Name (Bangla)", name: "bn_name", widget: "string" }
              - label: "Chapters"
                name: "chapters"
                widget: "list"
                summary: "{{fields.name}}"
                fields:
                  - { label: "Chapter ID", name: "id", widget: "string" }
                  - { label: "Chapter Name (English)", name: "name", widget: "string" }
                  - { label: "Chapter Name (Bangla)", name: "bn_name", widget: "string" }

          - label: "Videos"
            name: "videos"
            widget: "list"
            summary: "{{fields.title}} (ID: {{fields.key}})"
            fields:
              - { label: "Video Key (Unique ID)", name: "key", widget: "string" }
              - { label: "Chapter ID", name: "chapterId", widget: "string" }
              - { label: "Video Title", name: "title", widget: "string" }
              - { label: "YouTube Video ID", name: "youtubeId", widget: "string" }
              - label: "Instructor"
                name: "instructor"
                widget: "object"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
              - label: "Downloads"
                name: "downloads"
                widget: "object"
                fields:
                  - { label: "Lecture Sheet URL", name: "lectureSheet", widget: "string", required: false }
              - label: "Slide URL (For One Shot)"
                name: "slideUrl"
                widget: "string"
                required: false
